<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Favorites</name>
   <tag></tag>
   <elementGuidId>d6affaa9-6509-46cf-a2c2-4840cfdd0dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_stkMain >> internal:text=&quot;Favorites&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ce72f9c2-82ae-460b-be52-1038f01eb075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Stacks-CAPTION:a:b</value>
      <webElementGuid>825c96d2-a965-42be-859d-fcbc6819dfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-stacks-caption xui-title-node     xui-custom</value>
      <webElementGuid>e3cb8d7f-077c-4648-9045-a7a3969b760a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorites</value>
      <webElementGuid>504d0803-7c8c-44fa-894b-2c516077419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Stacks-CAPTION:a:b&quot;)</value>
      <webElementGuid>45254350-de23-4498-8ff9-94ff96899259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      <webElementGuid>17b8c2c3-f48c-4dc9-a370-dac7ed135b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Stacks-IBWRAP:a:b']/span[5]</value>
      <webElementGuid>6f1850a6-036f-4515-9c08-0e7d61085870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[3]/following::span[14]</value>
      <webElementGuid>52a4816b-ba4e-4a08-8c74-d4a04eb9f7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[2]/following::span[25]</value>
      <webElementGuid>95ed0645-998c-4f35-bf45-9ceabc53e8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferences'])[2]/preceding::span[10]</value>
      <webElementGuid>36a3c115-15f3-4611-9128-dbcf6504d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::span[24]</value>
      <webElementGuid>faf392c6-adbf-45e3-8e0f-e6b0dbff416e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span/div/span[5]</value>
      <webElementGuid>72a7c74f-1168-468f-9b06-3b310ebfe4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Stacks-CAPTION:a:b' and (text() = 'Favorites' or . = 'Favorites')]</value>
      <webElementGuid>36256633-3bc6-4764-83c2-fcd8e50cdb11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
