<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_O K (1)</name>
   <tag></tag>
   <elementGuidId>49a414c3-91ca-499f-ad3a-9510e31b682c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='xlid'])[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;O K&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a69de33-5867-42b0-b9ee-a1caed81fe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xlid</value>
      <webElementGuid>0d32bac6-9f38-46d0-8f35-1b65c70775c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline.ok</value>
      <webElementGuid>f0c5d63e-c2bf-4c84-be78-7e4e33c9728a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>O K</value>
      <webElementGuid>3a230e6d-1cc1-4c5d-81e9-6d65c182f5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Button-CAPTION:ak:&quot;)/span[@id=&quot;xlid&quot;]</value>
      <webElementGuid>8eff8f26-1648-4b4e-aaf9-b73b7f072516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='xlid'])[20]</value>
      <webElementGuid>3641bce2-4b3c-4472-ae22-c07c01d5b47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Button-CAPTION:ak:']/span</value>
      <webElementGuid>82b8e00a-88f1-4eb6-8fb2-5f8d8059b474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INFORMASI'])[2]/following::span[13]</value>
      <webElementGuid>6af3cea5-039f-4676-98c1-41aa645ee2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUBERTUS KENNETH'])[4]/following::span[27]</value>
      <webElementGuid>72e1db2b-eed6-4c04-80b5-9cfd1f2bd176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[SC0005] Berhasil setujui data.'])[1]/preceding::span[2]</value>
      <webElementGuid>f89b8e32-98ed-4fd1-9ddf-e0208c253aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='O K']/parent::*</value>
      <webElementGuid>3b9fcafe-2df0-466b-9cd1-bf2bc3552ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]/span</value>
      <webElementGuid>93af01c4-40d8-467c-bccd-a9f985b7b0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xlid' and (text() = 'O K' or . = 'O K')]</value>
      <webElementGuid>004240d1-3126-443a-9089-4515d452c35c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
