<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DATA REKENINGAMB - PRODUK AMBBNK12 - KE_d03922</name>
   <tag></tag>
   <elementGuidId>ad4ce26e-3cc1-4345-a2f5-b080cd7b60ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui.UI.Div:ag:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DATA REKENINGAMB - PRODUK AMBBNK12 - KENNETH TESTCB - ANDREW-COBADA - D.NAS-1 BL&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66be79fc-f50d-4493-a666-5bdcb11255d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>7cfd1a96-d76a-45c8-9de1-dcdf1712b611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Div:ag:</value>
      <webElementGuid>75ba0e77-dbed-46fc-bccf-63d63d809d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-div xui-div xui-uicontainer xui-ui-ctrl xui-ui-selectable xui-custom xui-css-noscrollx</value>
      <webElementGuid>531bc32f-eb59-40be-9cc7-91a582232e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DATA REKENINGAMB - PRODUK AMBBNK12 - KENNETH TESTCB - ANDREW-COBADA - D.NAS-1 BLDB - D.NAS-3 BLNDC - D.NAS-6 BLDD - D.NAS-12BLNDE - D.HDH 12BLDF - D.HDH 6BLDFF - KEN TESTDG - D.HDH 12BLDH - D.VCH-3 BLDI - D.VCH-6 BLDJ - D.VCH 12BLDK - D.KHUS-1 BDR - TEST RIRIDTC - KEN TESTGT - GREG-TESTMT - MIA TESTPC - KENNETH TESTPCA - KEN TESTRRE - TEST HADIAHJenis Produk*Nama Pada RekeningTgl. Buka RekeningTgl. Jatuh TempoTgl Mulai Berlaku ProdukTgl Mulai Berlaku ProdukNomor Bilyet Tercetak*Nominal*Tgl. Bunga BerikutTgl Mulai Berlaku ProdukSuku Bunga Produk*VarianceBunga Efektif*1 - TUNAI2 - ARO3 - KREDIT REKENING4 - KREDIT KE BANK LAINCara Pengkreditan Bunga*Nama Bank*CabangNo. Rek Kredit Bunga*Nama Pemilik Rek. Pengkreditan Bunga*1 - TUNAI2 - ARO3 - KREDIT KE REKENING LAIN4 - TRANSFER KE BANK LAINCara Pengkreditan Pokok*Nama Bank*CabangNo. Rek Kredit Pokok*Nama Pemilik Rek. Pengkreditan Pokok*Kirim Advis Jatuh TempoMetode Advis Jatuh TempoAlamat**Petugas MarketingKantor KasPilih Nomor RekeningNama InstansiCatatanText Area</value>
      <webElementGuid>5a53861d-6e53-4958-9b99-806c7323420e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Div:ag:&quot;)</value>
      <webElementGuid>3afa9eaa-55f6-4ac7-9010-fdcdac184320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:ag:']</value>
      <webElementGuid>32a0b6d5-adfd-4c6f-8d33-85f14e349f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Div:z:']/div[2]</value>
      <webElementGuid>39d7d05f-ebe1-401c-95bb-71b036ed80c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Alternatif'])[1]/following::div[2]</value>
      <webElementGuid>75e4ab93-c21f-447e-9b67-7ebe17fa63eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Utama'])[1]/following::div[4]</value>
      <webElementGuid>32b96887-c5e6-4094-ae9c-45e0990b4128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]</value>
      <webElementGuid>278583f4-df05-4170-a0b1-6c4bc60e5607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui.UI.Div:ag:' and (text() = 'DATA REKENINGAMB - PRODUK AMBBNK12 - KENNETH TESTCB - ANDREW-COBADA - D.NAS-1 BLDB - D.NAS-3 BLNDC - D.NAS-6 BLDD - D.NAS-12BLNDE - D.HDH 12BLDF - D.HDH 6BLDFF - KEN TESTDG - D.HDH 12BLDH - D.VCH-3 BLDI - D.VCH-6 BLDJ - D.VCH 12BLDK - D.KHUS-1 BDR - TEST RIRIDTC - KEN TESTGT - GREG-TESTMT - MIA TESTPC - KENNETH TESTPCA - KEN TESTRRE - TEST HADIAHJenis Produk*Nama Pada RekeningTgl. Buka RekeningTgl. Jatuh TempoTgl Mulai Berlaku ProdukTgl Mulai Berlaku ProdukNomor Bilyet Tercetak*Nominal*Tgl. Bunga BerikutTgl Mulai Berlaku ProdukSuku Bunga Produk*VarianceBunga Efektif*1 - TUNAI2 - ARO3 - KREDIT REKENING4 - KREDIT KE BANK LAINCara Pengkreditan Bunga*Nama Bank*CabangNo. Rek Kredit Bunga*Nama Pemilik Rek. Pengkreditan Bunga*1 - TUNAI2 - ARO3 - KREDIT KE REKENING LAIN4 - TRANSFER KE BANK LAINCara Pengkreditan Pokok*Nama Bank*CabangNo. Rek Kredit Pokok*Nama Pemilik Rek. Pengkreditan Pokok*Kirim Advis Jatuh TempoMetode Advis Jatuh TempoAlamat**Petugas MarketingKantor KasPilih Nomor RekeningNama InstansiCatatanText Area' or . = 'DATA REKENINGAMB - PRODUK AMBBNK12 - KENNETH TESTCB - ANDREW-COBADA - D.NAS-1 BLDB - D.NAS-3 BLNDC - D.NAS-6 BLDD - D.NAS-12BLNDE - D.HDH 12BLDF - D.HDH 6BLDFF - KEN TESTDG - D.HDH 12BLDH - D.VCH-3 BLDI - D.VCH-6 BLDJ - D.VCH 12BLDK - D.KHUS-1 BDR - TEST RIRIDTC - KEN TESTGT - GREG-TESTMT - MIA TESTPC - KENNETH TESTPCA - KEN TESTRRE - TEST HADIAHJenis Produk*Nama Pada RekeningTgl. Buka RekeningTgl. Jatuh TempoTgl Mulai Berlaku ProdukTgl Mulai Berlaku ProdukNomor Bilyet Tercetak*Nominal*Tgl. Bunga BerikutTgl Mulai Berlaku ProdukSuku Bunga Produk*VarianceBunga Efektif*1 - TUNAI2 - ARO3 - KREDIT REKENING4 - KREDIT KE BANK LAINCara Pengkreditan Bunga*Nama Bank*CabangNo. Rek Kredit Bunga*Nama Pemilik Rek. Pengkreditan Bunga*1 - TUNAI2 - ARO3 - KREDIT KE REKENING LAIN4 - TRANSFER KE BANK LAINCara Pengkreditan Pokok*Nama Bank*CabangNo. Rek Kredit Pokok*Nama Pemilik Rek. Pengkreditan Pokok*Kirim Advis Jatuh TempoMetode Advis Jatuh TempoAlamat**Petugas MarketingKantor KasPilih Nomor RekeningNama InstansiCatatanText Area')]</value>
      <webElementGuid>0a05f7e8-fdf5-4f09-b011-8bab9bc15873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
