<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Add_xui.UI.Input-INPUTd</name>
   <tag></tag>
   <elementGuidId>60a6c962-7312-472a-a0cc-b0afd64bd3e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='xui.UI.Input-INPUT:d:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>49e2ecbb-9872-49ac-93ba-8a3c6c77895f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f087e78-2e02-4aa8-b52b-4f4dfb1bda83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5013abb4-cd11-4a2d-9b6c-52c0bf754e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>33117c42-ace3-4d7c-a7c9-3a9f033848ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Input-INPUT:d:</value>
      <webElementGuid>c701fcd2-755c-485b-b384-149245b4e74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-ui-reset xui-node-textarea xui-input-input xui-ui-ellipsis      xui-custom</value>
      <webElementGuid>b5fd8495-84a5-442e-bc0f-d3f95918b628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Input-INPUT:d:&quot;)</value>
      <webElementGuid>0c14e349-4fc2-4c5e-8baa-674b65c7ac97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='xui.UI.Input-INPUT:d:']</value>
      <webElementGuid>5b57564d-8133-429a-b22f-72af3d6bf562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Input-WRAP:d:']/textarea</value>
      <webElementGuid>9c1e2f5a-695a-4131-b20d-3d78e00c8ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>368dd778-8cf3-4328-b2b0-787e7dcd5404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'xui.UI.Input-INPUT:d:']</value>
      <webElementGuid>5206fe01-7bf8-4be9-b5ee-df8f7d92e146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
