<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>e528b91c-d18e-41ee-a51c-d3a633f5018b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xui.UI.DatePicker-TD:d:3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;1&quot;s] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d0fab9c0-0f9a-4f29-9d2d-42fc7616d308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.DatePicker-TD:d:3</value>
      <webElementGuid>2e9c7fc1-5585-4a9e-b7de-b509b1ab9b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-uicell xui-uicell-hover xui-node-td xui-node-td-hover xui-uiborder-b xui-uiborder-b-hover xui-uiborder-r xui-uiborder-r-hover xui-datepicker-td xui-datepicker-td-hover xui-custom xui-custom-hover </value>
      <webElementGuid>2829462e-b298-4385-83a5-99b7df8d5807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>96e7e27e-cf38-49bb-a6ef-7803dc168fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.DatePicker-TD:d:3&quot;)</value>
      <webElementGuid>eecb6496-0ae6-43db-9efc-988947caf3f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xui.UI.DatePicker-TD:d:3']</value>
      <webElementGuid>0178e3c9-ac41-4dd2-a3c9-8af664f823f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='xui.UI.DatePicker-TBODY:d:']/tr/td[4]</value>
      <webElementGuid>9a5af764-a98d-40fe-9804-833bf33ab3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[3]/following::td[4]</value>
      <webElementGuid>2dce96a0-f34f-4156-88d1-caf1af5b0c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[3]/following::td[4]</value>
      <webElementGuid>7d1bab6b-2b77-43d5-a25b-98f552fdf268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/preceding::td[39]</value>
      <webElementGuid>93ab2e9d-4dc0-484e-bedf-75aca70cbab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SET'])[3]/preceding::td[39]</value>
      <webElementGuid>24aa179e-cff8-402a-acb2-818889053abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>574831e7-efc0-4c8d-a851-5956ff608685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xui.UI.DatePicker-TD:d:3' and (text() = '1' or . = '1')]</value>
      <webElementGuid>dc9de689-c210-43bc-90e6-88268215cf54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
