<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1 (1)</name>
   <tag></tag>
   <elementGuidId>95036627-b953-4c8e-835f-41ec4ff69b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xui.UI.DatePicker-TD:d:3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;1&quot;s] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>96603210-40b4-42b1-8c5e-2f74d9bc4670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.DatePicker-TD:d:3</value>
      <webElementGuid>887b97f7-0fc4-402b-8a47-bf43f1074ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-uicell xui-uicell-hover xui-node-td xui-node-td-hover xui-uiborder-b xui-uiborder-b-hover xui-uiborder-r xui-uiborder-r-hover xui-datepicker-td xui-datepicker-td-hover xui-custom xui-custom-hover </value>
      <webElementGuid>0123c27c-3183-4a1c-91de-76200b013bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8140c79e-92dd-418a-933e-95e275cec65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.DatePicker-TD:d:3&quot;)</value>
      <webElementGuid>3e73059e-d10e-4c02-8ac1-563ee59f83a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xui.UI.DatePicker-TD:d:3']</value>
      <webElementGuid>b0941acb-2303-437e-b4a1-ffcdfaebde79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='xui.UI.DatePicker-TBODY:d:']/tr/td[4]</value>
      <webElementGuid>6d64bff6-bd59-4e97-a40e-e29db2a17c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[3]/following::td[4]</value>
      <webElementGuid>407f5f60-693f-4426-aa8a-ec32d84abdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[3]/following::td[4]</value>
      <webElementGuid>ef77dd67-4ea9-4dc7-8c48-5de855e4f64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/preceding::td[39]</value>
      <webElementGuid>196d039c-110d-4f44-8ab0-54a2bd1551e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SET'])[3]/preceding::td[39]</value>
      <webElementGuid>ad448a6a-131d-44d4-a174-14c2bc0fae43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>092a8381-607f-41c3-8bf0-88cd9195bd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xui.UI.DatePicker-TD:d:3' and (text() = '1' or . = '1')]</value>
      <webElementGuid>01a1ca67-234e-4ee0-9034-29fb7f9898eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
