<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Simpan (1)</name>
   <tag></tag>
   <elementGuidId>e71fd840-8d53-4e0c-802a-97f3a5b899ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.StatusButtons-CAPTION:a:b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Simpan&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f1e801e-dc27-4a4a-8557-452637c961ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.StatusButtons-CAPTION:a:b</value>
      <webElementGuid>d39cc3f1-e41e-4ce0-b2f9-236950226178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-statusbuttons-caption     xui-custom</value>
      <webElementGuid>5ca65a33-b58d-49b6-94df-87f82e3b4033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>66131a75-eb8b-4be6-9c0d-7962b2a6c57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.StatusButtons-CAPTION:a:b&quot;)</value>
      <webElementGuid>c197ea46-9d82-46bd-89a5-da09c9070cd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.StatusButtons-CAPTION:a:b']</value>
      <webElementGuid>01de4328-c994-46b1-9782-777acc0f7d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.StatusButtons-ITEM:a:b']/span[3]</value>
      <webElementGuid>958a8136-a31f-48dd-b1bd-67f429b98263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::span[7]</value>
      <webElementGuid>ca460b12-d3a1-47d1-9337-429489916c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HUBERTUS KENNETH'])[1]/following::span[27]</value>
      <webElementGuid>e69dbbf6-a222-42d7-bd28-5eb07b2e6f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/preceding::span[11]</value>
      <webElementGuid>1559b62d-3ad4-49fb-9352-26cfd57f5348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Bayar Bunga'])[1]/preceding::span[15]</value>
      <webElementGuid>bf79511e-1dc4-4a92-9abe-1a9769f23cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>055b9d09-f44b-4bf3-9c08-2a4efb96b94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span[2]/span[3]</value>
      <webElementGuid>df35dcd7-4f09-4a3e-b0ce-fe7d8e848cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.StatusButtons-CAPTION:a:b' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>46a8c32b-fc29-4f4f-92ac-488acab0a352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
