<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Password_xui.UI.ComboInput-BOXj (1)</name>
   <tag></tag>
   <elementGuidId>5b48213b-b38a-414a-95eb-c12a7be80d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.ComboInput-BOX:j:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;xui\.UI\.ComboInput-BOX\:j\:&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b151584-71c0-464d-8bb1-961c8841a2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.ComboInput-BOX:j:</value>
      <webElementGuid>c83edce4-2ac8-4d87-a59a-de91d6f35c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-span xui-node-span-hover xui-comboinput-box xui-comboinput-box-hover xui-ui-input xui-ui-input-hover xui-ui-shadow-input xui-ui-shadow-input-hover xui-uiborder-flat xui-uiborder-flat-hover xui-uibase xui-uibase-hover xui-uiborder-radius xui-uiborder-radius-hover xui-custom xui-custom-hover</value>
      <webElementGuid>9c7cb97f-9a87-4e53-a68d-f120788091ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.ComboInput-BOX:j:&quot;)</value>
      <webElementGuid>0e045bd4-926e-4cfa-a8e2-5855be8e4fda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ComboInput-BOX:j:']</value>
      <webElementGuid>ae985b4c-5f2a-4f90-9bd0-06a2b025e29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.ComboInput-BORDER:j:']/span[2]</value>
      <webElementGuid>00e54a6e-c57a-4552-b0bf-965ca3b27f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[1]</value>
      <webElementGuid>e526db68-4be8-4569-b9a4-4258c0b831d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::span[8]</value>
      <webElementGuid>f0f1d1af-8147-44ed-b01b-04dcc96a9bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI Theme'])[1]/preceding::span[6]</value>
      <webElementGuid>0da6e913-8f91-4de1-b79e-bdf9ba81a435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font Size'])[2]/preceding::span[16]</value>
      <webElementGuid>e36ee1fd-e6b7-493b-ae22-c24735e53f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span[3]/span/span[3]/span[2]</value>
      <webElementGuid>bea2be59-2e38-40d9-9a80-a6a9061c8323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.ComboInput-BOX:j:']</value>
      <webElementGuid>b7191a71-1238-47ae-b7bd-e937584a6215</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
