<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_999,999,999,999,999.99</name>
   <tag></tag>
   <elementGuidId>761c9b3a-73ac-4b91-8e9e-faca2583b683</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.TreeGrid-CELLCAPTION:o:-c_g']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;999,999,999,999,999.99&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5d5bf60-b26e-4bfe-9b31-49670f3db88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CELLCAPTION:o:-c_g</value>
      <webElementGuid>c82a718d-24d9-4efb-8066-9c1f2931fb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-treegrid-cellcaption xui-v-node     xui-custom</value>
      <webElementGuid>aad6b99c-708a-4387-b900-dc3b55839a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 999,999,999,999,999.99</value>
      <webElementGuid>c6c1292d-029f-4ea1-afee-9a7531ab826b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CELLCAPTION:o:-c_g&quot;)</value>
      <webElementGuid>b98d1672-9b05-400d-9503-e53d4036df88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLCAPTION:o:-c_g']</value>
      <webElementGuid>e42d126f-3416-4208-80d8-46307f4b719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-CELLA:o:-c_g']/span</value>
      <webElementGuid>97793a6c-2284-491b-817c-fb2bd5d25c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Narasi'])[1]/following::span[40]</value>
      <webElementGuid>162ad87b-5881-41fd-ba92-93cc2d87607a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Nominal'])[1]/following::span[44]</value>
      <webElementGuid>ca54a51d-94d0-4163-8b03-13fc3ab57360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SETOR TUNAI 370300115673 A/N ABDULLAH ROCHIMAH, BUDI, HUBERTUS KENNETH, DITA AKMANDA, RIRI AKMANDA'])[1]/preceding::span[1]</value>
      <webElementGuid>444c30d8-326a-4f59-9c0a-46b923fd2aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL DANA'])[1]/preceding::span[10]</value>
      <webElementGuid>6f60a914-dae2-46cc-b497-8f7859d5083a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/table/tbody/tr[3]/td[2]/div/div/div/div/div/span[7]/span/span</value>
      <webElementGuid>d0bd241c-c2e8-4f78-a527-251115876800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.TreeGrid-CELLCAPTION:o:-c_g' and (text() = ' 999,999,999,999,999.99' or . = ' 999,999,999,999,999.99')]</value>
      <webElementGuid>3fe04f63-3be8-41b6-b169-7789a10b26d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
