<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DATA SALDO</name>
   <tag></tag>
   <elementGuidId>bf0f221a-0852-4357-8f12-79982e405a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Tabs-CAPTION:a:d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;DATA SALDO&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18f2bf92-0533-49c6-b2c4-573d0ed354b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Tabs-CAPTION:a:d</value>
      <webElementGuid>da3045b4-8f29-453d-8685-1d33ca42da06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-tabs-caption xui-title-node     xui-custom</value>
      <webElementGuid>c7e75efb-ee53-416e-9c89-915c896b7fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DATA SALDO</value>
      <webElementGuid>bc42eeac-da39-48ba-b5e8-1c35f89543cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Tabs-CAPTION:a:d&quot;)</value>
      <webElementGuid>ec27c524-09bc-47d7-98d1-66fffd301a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Tabs-CAPTION:a:d']</value>
      <webElementGuid>5befd198-b145-42b2-84a6-6a87af79f54d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Tabs-IBWRAP:a:d']/span[4]</value>
      <webElementGuid>3eef93db-00f0-450a-9277-98326052c4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA KUASA'])[1]/following::span[13]</value>
      <webElementGuid>cc433e7e-c584-438c-a30f-7ac84cc898ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REKENING BERJANGKA'])[1]/following::span[26]</value>
      <webElementGuid>8ed99132-d845-4f7b-86b4-4a26421a5f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HISTORY BUNGA'])[1]/preceding::span[9]</value>
      <webElementGuid>80d0c2c1-7ea2-42fb-91b0-6ab18996df84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kantor Pemilik Rekening'])[1]/preceding::span[21]</value>
      <webElementGuid>142e4460-ab8a-4292-a2b3-6c7664b495d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DATA SALDO']/parent::*</value>
      <webElementGuid>62b735fc-f9b5-4ccb-8350-9da8937ae5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/span/span/span/div/span[4]</value>
      <webElementGuid>549c2381-a02d-473c-8532-57b9adb9625a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Tabs-CAPTION:a:d' and (text() = 'DATA SALDO' or . = 'DATA SALDO')]</value>
      <webElementGuid>4eef9bd5-3171-413e-b747-79969d6893d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
