<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ya</name>
   <tag></tag>
   <elementGuidId>7eff0349-eb9a-486d-8c88-1e56be163e01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Button-CAPTION:ab:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ya&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab42a17c-f37f-4108-b26b-4e2af4798808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Button-CAPTION:ab:</value>
      <webElementGuid>0c5501e3-d9ad-4814-8016-e3d89d88a7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-button-caption     xui-custom</value>
      <webElementGuid>9b521dbb-e5cd-426d-beed-b46973ac9ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Ya  </value>
      <webElementGuid>02d9d6f3-2a4d-4f85-accf-f7a78b538fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Button-CAPTION:ab:&quot;)</value>
      <webElementGuid>cd210403-65de-40b9-aca2-853c1cc07b7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Button-CAPTION:ab:']</value>
      <webElementGuid>eaf9bb8c-e854-48de-8ce4-019871efe849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='xui.UI.Button:ab:']/span[2]</value>
      <webElementGuid>6350990a-c9a2-473f-a0c1-92a88635fbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi'])[1]/following::span[15]</value>
      <webElementGuid>eef74f07-e026-405e-8757-f8c62e57060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data akan disimpan?'])[1]/preceding::span[2]</value>
      <webElementGuid>8da5889f-4b6c-49ed-b8b4-b46129925277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Favorite'])[1]/preceding::span[16]</value>
      <webElementGuid>bf75c64b-c051-42c5-a7f7-b0bac28832b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[2]</value>
      <webElementGuid>76289566-d9b7-44c4-8fe9-c09964b5c9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Button-CAPTION:ab:' and (text() = '  Ya  ' or . = '  Ya  ')]</value>
      <webElementGuid>bb495372-c676-42cd-a7f8-ae836ff61c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
