<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ID Product_xui.UI.TreeGrid-CMDa-r_a_edit</name>
   <tag></tag>
   <elementGuidId>01b300c4-dc78-4211-b82a-34d5507565db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_a_edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c0db2cfc-1da1-4e0a-8941-76191b173e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>05eb5305-49a1-4ca2-9671-4bd43a8fca53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea65d275-dcb8-485e-a951-8628568fb09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.TreeGrid-CMD:a:-r_a_edit</value>
      <webElementGuid>3d635607-1ca1-4a9d-ad35-3c739553b459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-node-image xui-node-image-hover xui-treegrid-cmd xui-treegrid-cmd-hover xui-node xui-node-hover xui-tag-cmd xui-tag-cmd-hover fa fa-hover fa-lg fa-lg-hover fa-edit fa-edit-hover xui-custom xui-custom-hover</value>
      <webElementGuid>2299d47b-b1df-4bd4-a7f5-15e9949692cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.TreeGrid-CMD:a:-r_a_edit&quot;)</value>
      <webElementGuid>9b34fa25-1a80-4238-818a-17411cb10ba7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='xui.UI.TreeGrid-CMD:a:-r_a_edit']</value>
      <webElementGuid>fd8b595d-4342-4117-b0c7-41109ae30b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.TreeGrid-LTAGCMDS:a:-r_a']/img</value>
      <webElementGuid>57df33d5-4e04-4fc2-a126-b387300b2ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Edit']</value>
      <webElementGuid>e424eec7-65df-4a91-860e-68b60e2f65c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
      <webElementGuid>c9d3be7a-7adf-420b-a11a-c6a5f0266cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Edit' and @id = 'xui.UI.TreeGrid-CMD:a:-r_a_edit']</value>
      <webElementGuid>8e9c5e34-d81f-4c4f-8f89-2559581116f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
