<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DFF_xui_ab</name>
   <tag></tag>
   <elementGuidId>6b5d99a0-08db-4c0a-8aa6-6f61b1c77174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xui_ab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#xui_ab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#xui_ab</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f795d129-994d-4f71-91ea-99b1c043f6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-cover xui-custom xui-cover-modal xui-ui-unselectable</value>
      <webElementGuid>c83fa2af-7ea4-4892-99d2-d075244d2804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui_ab</value>
      <webElementGuid>6122f1df-a99b-4084-afdb-0b0f7bead550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui_ab&quot;)</value>
      <webElementGuid>37790b7d-3fc6-4103-af14-65cb3cb68c3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='xui_ab']</value>
      <webElementGuid>93ee1c47-3d27-4d35-8d6d-37515f7ad021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='xui_a']/div[8]</value>
      <webElementGuid>c18f390a-9dc6-4469-8173-4164b7a2fcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>828b4862-be81-4e8e-88b9-ee130754fa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'xui_ab']</value>
      <webElementGuid>35a132e7-0b2d-4255-abef-c245791dc062</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
