<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Favorites</name>
   <tag></tag>
   <elementGuidId>3eec54e3-92f2-4f3c-b4d3-91f9459b20c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl_stkMain >> internal:text=&quot;Favorites&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1de1fb1e-a40f-4138-8bcc-bd494538f6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.Stacks-CAPTION:a:b</value>
      <webElementGuid>57b28f61-5529-409e-91ab-eb239b89927f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-span xui-stacks-caption xui-title-node     xui-custom</value>
      <webElementGuid>2be02f94-43ff-4af5-9c29-0e35206b8502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorites</value>
      <webElementGuid>a1956263-f064-4c2b-a9e9-088d3a353e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.Stacks-CAPTION:a:b&quot;)</value>
      <webElementGuid>514a7f8d-cbbb-4f91-adda-3a50fcea54c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='xui.UI.Stacks-CAPTION:a:b']</value>
      <webElementGuid>f29a6ed9-062a-4f1b-82ae-685a8200a221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xui.UI.Stacks-IBWRAP:a:b']/span[5]</value>
      <webElementGuid>5d8976b0-2aaa-4ddb-8dbb-f271ae5441e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[3]/following::span[14]</value>
      <webElementGuid>3cfccb05-8b55-47b4-bcf0-e5be2e39c0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Main Menu'])[2]/following::span[25]</value>
      <webElementGuid>bd9e07a4-da39-441d-b738-fcdfbbeab1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferences'])[2]/preceding::span[10]</value>
      <webElementGuid>244e8371-42dd-4456-b873-159a055a3270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::span[24]</value>
      <webElementGuid>37d856cf-e311-4681-a9d7-2854044f3edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/span/div/span[5]</value>
      <webElementGuid>52675b02-7086-4688-9ed3-527ed5380186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'xui.UI.Stacks-CAPTION:a:b' and (text() = 'Favorites' or . = 'Favorites')]</value>
      <webElementGuid>373d50ac-9c42-48b2-98b7-ca1c09f7c18e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
