<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_5</name>
   <tag></tag>
   <elementGuidId>ef463db5-64f1-4a8a-84af-c0588d5e56bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='xui.UI.DatePicker-TD:d:7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;5&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5c54f17f-433f-4638-91a3-e0c39755abd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>xui.UI.DatePicker-TD:d:7</value>
      <webElementGuid>7ce237e8-77f5-442e-9fb2-193ac77a5e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xui-node xui-node-hover xui-uicell xui-uicell-hover xui-node-td xui-node-td-hover xui-uiborder-b xui-uiborder-b-hover xui-uiborder-r xui-uiborder-r-hover xui-datepicker-td xui-datepicker-td-hover xui-custom xui-custom-hover xui-uicell-alt xui-uicell-alt-hover</value>
      <webElementGuid>217b638f-1140-4f12-bf47-70cc890d6d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1b2ea682-9bee-4552-9efe-4eb7ba92dc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xui.UI.DatePicker-TD:d:7&quot;)</value>
      <webElementGuid>df89e197-93f1-428b-81dc-e7d466a4a2d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='xui.UI.DatePicker-TD:d:7']</value>
      <webElementGuid>a53a5934-a1c8-4c35-87e6-12c4798c64a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='xui.UI.DatePicker-TBODY:d:']/tr[2]/td</value>
      <webElementGuid>f1b25f47-7fe3-4757-a470-3785b03e28e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[3]/following::td[8]</value>
      <webElementGuid>36e6b49d-b238-43d6-8d3c-38ec386b4455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[3]/following::td[8]</value>
      <webElementGuid>6ee8bdd9-8537-406e-8920-f990c3ce2a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/preceding::td[35]</value>
      <webElementGuid>c7ae419a-fa24-44ed-b863-39d553c33bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SET'])[3]/preceding::td[35]</value>
      <webElementGuid>c77de603-d8a1-4231-b1cf-fef979349d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/table/tbody/tr[2]/td</value>
      <webElementGuid>6ed5489e-9ca5-4d4f-9423-01e0355913ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'xui.UI.DatePicker-TD:d:7' and (text() = '5' or . = '5')]</value>
      <webElementGuid>d19f6a58-3744-411f-ac8d-1f6a58544114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
